from fastapi_storages import S3Storage
from app.env import AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_S3_BUCKET_NAME, \
    AWS_S3_ENDPOINT_URL, AWS_DEFAULT_ACL, AWS_S3_USE_SSL


class PublicAssetS3Storage(S3Storage):
    AWS_ACCESS_KEY_ID = AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = AWS_SECRET_ACCESS_KEY
    AWS_S3_BUCKET_NAME = AWS_S3_BUCKET_NAME
    AWS_S3_ENDPOINT_URL = AWS_S3_ENDPOINT_URL
    AWS_DEFAULT_ACL = AWS_DEFAULT_ACL
    AWS_S3_USE_SSL = AWS_S3_USE_SSL
