{{- if $.Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/component: {{ $.Chart.Name }}
data:
  {{- range $k, $v := $.Values.config.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
{{- end }}
