{{- range $name, $app := .Values.apps }}
{{- if $app.has_hook }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ $.Chart.Name }}-migrator
  name: {{ $.Chart.Name }}-migrator
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      {{- with $.Values.image.secrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: primary
        image: {{ $.Values.image.registry }}/{{ $.Values.image.name }}:{{ $.Values.image.tag | default $.Values.env.APP_VERSION }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        command:
          - "bash"
        args:
          - "-c"
          - "alembic upgrade head"
        {{- if or (and $.Values.config $.Values.config.data) (and $.Values.secrets $.Values.secrets.data) }}
        envFrom:
        {{- if (and $.Values.config $.Values.config.data)}}
          - configMapRef:
              name: {{ $.Chart.Name }}-config
        {{- end }}
        {{- if (and $.Values.secrets $.Values.secrets.data) }}
          - secretRef:
              name: {{ $.Chart.Name }}-secret
        {{- end }}
        {{- end }}
{{- end }}
{{- end }}