{{- if $.Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Chart.Name }}-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}
type: Opaque
data:
  {{- range $k, $v := $.Values.secrets.data }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}

---
{{- end }}
