{{- range $name, $app := $.Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Chart.Name }}-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}
type: Opaque
data:
  {{- range $k, $v := $app.data }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}

---
{{- end }}