ERC20_ABI = [
    {
        "name": "approve",
        "inputs": [
            {"internalType": "address", "name": "spender", "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
        ],
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
        ],
        "name": "mint",
        "payable": True,
        "stateMutability": "payable",
        "type": "function",
    },
    {
        "name": "allowance",
        "inputs": [
            {"internalType": "address", "name": "owner", "type": "address"},
            {"internalType": "address", "name": "spender", "type": "address"},
        ],
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
]
PRESALE_ABI = [
    {
        "type": "constructor",
        "name": "",
        "inputs": [
            {
                "type": "address",
                "name": "COIN_PRICE_FEED_",
                "internalType": "contract AggregatorV3Interface",
            },
            {"type": "address", "name": "usdcToken_", "internalType": "contract IERC20"},
            {"type": "address", "name": "usdtToken_", "internalType": "contract IERC20"},
            {"type": "address", "name": "protocolWallet_", "internalType": "address"},
            {"type": "address", "name": "admin", "internalType": "address"},
        ],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {"type": "error", "name": "EnforcedPause", "inputs": [], "outputs": []},
    {"type": "error", "name": "ExpectedPause", "inputs": [], "outputs": []},
    {
        "type": "error",
        "name": "OwnableInvalidOwner",
        "inputs": [{"type": "address", "name": "owner", "internalType": "address"}],
        "outputs": [],
    },
    {
        "type": "error",
        "name": "OwnableUnauthorizedAccount",
        "inputs": [{"type": "address", "name": "account", "internalType": "address"}],
        "outputs": [],
    },
    {"type": "error", "name": "SafeTransferFailed", "inputs": [], "outputs": []},
    {"type": "error", "name": "SafeTransferFromFailed", "inputs": [], "outputs": []},
    {
        "type": "event",
        "name": "OwnershipTransferred",
        "inputs": [
            {
                "type": "address",
                "name": "previousOwner",
                "indexed": True,
                "internalType": "address",
            },
            {"type": "address", "name": "newOwner", "indexed": True, "internalType": "address"},
        ],
        "outputs": [],
        "anonymous": False,
    },
    {
        "type": "event",
        "name": "Paused",
        "inputs": [
            {"type": "address", "name": "account", "indexed": False, "internalType": "address"}
        ],
        "outputs": [],
        "anonymous": False,
    },
    {
        "type": "event",
        "name": "StageUpdated",
        "inputs": [
            {"type": "uint256", "name": "currentStage", "indexed": False, "internalType": "uint256"}
        ],
        "outputs": [],
        "anonymous": False,
    },
    {
        "type": "event",
        "name": "TokensBought",
        "inputs": [
            {"type": "address", "name": "token", "indexed": True, "internalType": "address"},
            {"type": "address", "name": "user", "indexed": True, "internalType": "address"},
            {"type": "address", "name": "referrer", "indexed": True, "internalType": "address"},
            {"type": "uint256", "name": "amount", "indexed": False, "internalType": "uint256"},
        ],
        "outputs": [],
        "anonymous": False,
    },
    {
        "type": "event",
        "name": "Unpaused",
        "inputs": [
            {"type": "address", "name": "account", "indexed": False, "internalType": "address"}
        ],
        "outputs": [],
        "anonymous": False,
    },
    {
        "type": "function",
        "name": "COIN_DECIMALS",
        "inputs": [],
        "outputs": [{"type": "uint8", "name": "", "internalType": "uint8"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "COIN_PRICE_FEED",
        "inputs": [],
        "outputs": [
            {"type": "address", "name": "", "internalType": "contract AggregatorV3Interface"}
        ],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "PRICEFEED_DECIMALS",
        "inputs": [],
        "outputs": [{"type": "uint8", "name": "", "internalType": "uint8"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "STABLETOKEN_PRICE",
        "inputs": [],
        "outputs": [{"type": "int32", "name": "", "internalType": "int32"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "STABLE_TOKEN_DECIMALS",
        "inputs": [],
        "outputs": [{"type": "uint8", "name": "", "internalType": "uint8"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "balances",
        "inputs": [{"type": "address", "name": "user", "internalType": "address"}],
        "outputs": [{"type": "uint256", "name": "balance", "internalType": "uint256"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "depositCoin",
        "inputs": [{"type": "address", "name": "referrer", "internalType": "address"}],
        "outputs": [],
        "stateMutability": "payable",
    },
    {
        "type": "function",
        "name": "depositCoinTo",
        "inputs": [
            {"type": "address", "name": "to", "internalType": "address"},
            {"type": "address", "name": "referrer", "internalType": "address"},
        ],
        "outputs": [],
        "stateMutability": "payable",
    },
    {
        "type": "function",
        "name": "depositUSDC",
        "inputs": [
            {"type": "uint256", "name": "amount", "internalType": "uint256"},
            {"type": "address", "name": "referrer", "internalType": "address"},
        ],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "depositUSDCTo",
        "inputs": [
            {"type": "address", "name": "to", "internalType": "address"},
            {"type": "uint256", "name": "amount", "internalType": "uint256"},
            {"type": "address", "name": "referrer", "internalType": "address"},
        ],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "depositUSDT",
        "inputs": [
            {"type": "uint256", "name": "amount", "internalType": "uint256"},
            {"type": "address", "name": "referrer", "internalType": "address"},
        ],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "depositUSDTTo",
        "inputs": [
            {"type": "address", "name": "to", "internalType": "address"},
            {"type": "uint256", "name": "amount", "internalType": "uint256"},
            {"type": "address", "name": "referrer", "internalType": "address"},
        ],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "owner",
        "inputs": [],
        "outputs": [{"type": "address", "name": "", "internalType": "address"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "pause",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "paused",
        "inputs": [],
        "outputs": [{"type": "bool", "name": "", "internalType": "bool"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "protocolWallet",
        "inputs": [],
        "outputs": [{"type": "address", "name": "", "internalType": "address"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "renounceOwnership",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "setStage",
        "inputs": [{"type": "uint256", "name": "stageIterator_", "internalType": "uint256"}],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "stageIterator",
        "inputs": [],
        "outputs": [{"type": "uint256", "name": "", "internalType": "uint256"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "stages",
        "inputs": [{"type": "uint256", "name": "", "internalType": "uint256"}],
        "outputs": [
            {"type": "uint96", "name": "cost", "internalType": "uint96"},
            {"type": "uint160", "name": "amount", "internalType": "uint160"},
        ],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "totalSoldInUSD",
        "inputs": [],
        "outputs": [{"type": "uint256", "name": "", "internalType": "uint256"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "totalTokensSold",
        "inputs": [],
        "outputs": [{"type": "uint256", "name": "", "internalType": "uint256"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "transferOwnership",
        "inputs": [{"type": "address", "name": "newOwner", "internalType": "address"}],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "unpause",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "updateProtocolWallet",
        "inputs": [{"type": "address", "name": "wallet", "internalType": "address"}],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "updateTotalSold",
        "inputs": [{"type": "uint256", "name": "amount", "internalType": "uint256"}],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "usdcToken",
        "inputs": [],
        "outputs": [{"type": "address", "name": "", "internalType": "contract IERC20"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "usdtToken",
        "inputs": [],
        "outputs": [{"type": "address", "name": "", "internalType": "contract IERC20"}],
        "stateMutability": "view",
    },
]
PRESALE_BSC_ABI = [
    {
        "inputs": [
            {
                "internalType": "contract AggregatorV3Interface",
                "name": "COIN_PRICE_FEED_",
                "type": "address",
            },
            {"internalType": "contract IERC20", "name": "usdcToken_", "type": "address"},
            {"internalType": "contract IERC20", "name": "usdtToken_", "type": "address"},
            {"internalType": "address", "name": "protocolWallet_", "type": "address"},
            {"internalType": "address", "name": "admin", "type": "address"},
        ],
        "stateMutability": "nonpayable",
        "type": "constructor",
    },
    {"inputs": [], "name": "EnforcedPause", "type": "error"},
    {"inputs": [], "name": "ExpectedPause", "type": "error"},
    {
        "inputs": [{"internalType": "address", "name": "owner", "type": "address"}],
        "name": "OwnableInvalidOwner",
        "type": "error",
    },
    {
        "inputs": [{"internalType": "address", "name": "account", "type": "address"}],
        "name": "OwnableUnauthorizedAccount",
        "type": "error",
    },
    {"inputs": [], "name": "SafeTransferFailed", "type": "error"},
    {"inputs": [], "name": "SafeTransferFromFailed", "type": "error"},
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "internalType": "address",
                "name": "previousOwner",
                "type": "address",
            },
            {"indexed": True, "internalType": "address", "name": "newOwner", "type": "address"},
        ],
        "name": "OwnershipTransferred",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "internalType": "address", "name": "account", "type": "address"}
        ],
        "name": "Paused",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "internalType": "uint256", "name": "currentStage", "type": "uint256"}
        ],
        "name": "StageUpdated",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "token", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "user", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "referrer", "type": "address"},
            {"indexed": False, "internalType": "uint256", "name": "amount", "type": "uint256"},
        ],
        "name": "TokensBought",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "internalType": "address", "name": "account", "type": "address"}
        ],
        "name": "Unpaused",
        "type": "event",
    },
    {
        "inputs": [],
        "name": "COIN_PRICE_FEED",
        "outputs": [
            {"internalType": "contract AggregatorV3Interface", "name": "", "type": "address"}
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "PRICEFEED_DECIMALS",
        "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "STABLETOKEN_PRICE",
        "outputs": [{"internalType": "int32", "name": "", "type": "int32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "TOKEN_PRECISION",
        "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "user", "type": "address"}],
        "name": "balances",
        "outputs": [{"internalType": "uint256", "name": "balance", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "referrer", "type": "address"}],
        "name": "depositCoin",
        "outputs": [],
        "stateMutability": "payable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "address", "name": "referrer", "type": "address"},
        ],
        "name": "depositCoinTo",
        "outputs": [],
        "stateMutability": "payable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "address", "name": "referrer", "type": "address"},
        ],
        "name": "depositUSDC",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "address", "name": "referrer", "type": "address"},
        ],
        "name": "depositUSDCTo",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "address", "name": "referrer", "type": "address"},
        ],
        "name": "depositUSDT",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "address", "name": "referrer", "type": "address"},
        ],
        "name": "depositUSDTTo",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "owner",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "pause",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "paused",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "protocolWallet",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "renounceOwnership",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "contract IERC20", "name": "token", "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
        ],
        "name": "rescueFunds",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "stageIterator_", "type": "uint256"}],
        "name": "setStage",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "stageIterator",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "name": "stages",
        "outputs": [
            {"internalType": "uint96", "name": "cost", "type": "uint96"},
            {"internalType": "uint160", "name": "amount", "type": "uint160"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "totalSoldInUSD",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "totalTokensSold",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "newOwner", "type": "address"}],
        "name": "transferOwnership",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "unpause",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "wallet", "type": "address"}],
        "name": "updateProtocolWallet",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "amount", "type": "uint256"}],
        "name": "updateTotalSold",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "usdcToken",
        "outputs": [{"internalType": "contract IERC20", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "usdtToken",
        "outputs": [{"internalType": "contract IERC20", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
]
PRICE_FEED_ABI = [
    {
        "type": "constructor",
        "name": "",
        "inputs": [
            {"type": "address", "name": "_aggregator", "internalType": "address"},
            {"type": "address", "name": "_accessController", "internalType": "address"},
        ],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "event",
        "name": "AnswerUpdated",
        "inputs": [
            {"type": "int256", "name": "current", "indexed": True, "internalType": "int256"},
            {"type": "uint256", "name": "roundId", "indexed": True, "internalType": "uint256"},
            {"type": "uint256", "name": "updatedAt", "indexed": False, "internalType": "uint256"},
        ],
        "outputs": [],
        "anonymous": False,
    },
    {
        "type": "event",
        "name": "NewRound",
        "inputs": [
            {"type": "uint256", "name": "roundId", "indexed": True, "internalType": "uint256"},
            {"type": "address", "name": "startedBy", "indexed": True, "internalType": "address"},
            {"type": "uint256", "name": "startedAt", "indexed": False, "internalType": "uint256"},
        ],
        "outputs": [],
        "anonymous": False,
    },
    {
        "type": "event",
        "name": "OwnershipTransferRequested",
        "inputs": [
            {"type": "address", "name": "from", "indexed": True, "internalType": "address"},
            {"type": "address", "name": "to", "indexed": True, "internalType": "address"},
        ],
        "outputs": [],
        "anonymous": False,
    },
    {
        "type": "event",
        "name": "OwnershipTransferred",
        "inputs": [
            {"type": "address", "name": "from", "indexed": True, "internalType": "address"},
            {"type": "address", "name": "to", "indexed": True, "internalType": "address"},
        ],
        "outputs": [],
        "anonymous": False,
    },
    {
        "type": "function",
        "name": "acceptOwnership",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "accessController",
        "inputs": [],
        "outputs": [
            {"type": "address", "name": "", "internalType": "contract AccessControllerInterface"}
        ],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "aggregator",
        "inputs": [],
        "outputs": [{"type": "address", "name": "", "internalType": "address"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "confirmAggregator",
        "inputs": [{"type": "address", "name": "_aggregator", "internalType": "address"}],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "decimals",
        "inputs": [],
        "outputs": [{"type": "uint8", "name": "", "internalType": "uint8"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "description",
        "inputs": [],
        "outputs": [{"type": "string", "name": "", "internalType": "string"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "getAnswer",
        "inputs": [{"type": "uint256", "name": "_roundId", "internalType": "uint256"}],
        "outputs": [{"type": "int256", "name": "", "internalType": "int256"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "getRoundData",
        "inputs": [{"type": "uint80", "name": "_roundId", "internalType": "uint80"}],
        "outputs": [
            {"type": "uint80", "name": "roundId", "internalType": "uint80"},
            {"type": "int256", "name": "answer", "internalType": "int256"},
            {"type": "uint256", "name": "startedAt", "internalType": "uint256"},
            {"type": "uint256", "name": "updatedAt", "internalType": "uint256"},
            {"type": "uint80", "name": "answeredInRound", "internalType": "uint80"},
        ],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "getTimestamp",
        "inputs": [{"type": "uint256", "name": "_roundId", "internalType": "uint256"}],
        "outputs": [{"type": "uint256", "name": "", "internalType": "uint256"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "latestAnswer",
        "inputs": [],
        "outputs": [{"type": "int256", "name": "", "internalType": "int256"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "latestRound",
        "inputs": [],
        "outputs": [{"type": "uint256", "name": "", "internalType": "uint256"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "latestRoundData",
        "inputs": [],
        "outputs": [
            {"type": "uint80", "name": "roundId", "internalType": "uint80"},
            {"type": "int256", "name": "answer", "internalType": "int256"},
            {"type": "uint256", "name": "startedAt", "internalType": "uint256"},
            {"type": "uint256", "name": "updatedAt", "internalType": "uint256"},
            {"type": "uint80", "name": "answeredInRound", "internalType": "uint80"},
        ],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "latestTimestamp",
        "inputs": [],
        "outputs": [{"type": "uint256", "name": "", "internalType": "uint256"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "owner",
        "inputs": [],
        "outputs": [{"type": "address", "name": "", "internalType": "address payable"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "phaseAggregators",
        "inputs": [{"type": "uint16", "name": "", "internalType": "uint16"}],
        "outputs": [
            {"type": "address", "name": "", "internalType": "contract AggregatorV2V3Interface"}
        ],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "phaseId",
        "inputs": [],
        "outputs": [{"type": "uint16", "name": "", "internalType": "uint16"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "proposeAggregator",
        "inputs": [{"type": "address", "name": "_aggregator", "internalType": "address"}],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "proposedAggregator",
        "inputs": [],
        "outputs": [
            {"type": "address", "name": "", "internalType": "contract AggregatorV2V3Interface"}
        ],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "proposedGetRoundData",
        "inputs": [{"type": "uint80", "name": "_roundId", "internalType": "uint80"}],
        "outputs": [
            {"type": "uint80", "name": "roundId", "internalType": "uint80"},
            {"type": "int256", "name": "answer", "internalType": "int256"},
            {"type": "uint256", "name": "startedAt", "internalType": "uint256"},
            {"type": "uint256", "name": "updatedAt", "internalType": "uint256"},
            {"type": "uint80", "name": "answeredInRound", "internalType": "uint80"},
        ],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "proposedLatestRoundData",
        "inputs": [],
        "outputs": [
            {"type": "uint80", "name": "roundId", "internalType": "uint80"},
            {"type": "int256", "name": "answer", "internalType": "int256"},
            {"type": "uint256", "name": "startedAt", "internalType": "uint256"},
            {"type": "uint256", "name": "updatedAt", "internalType": "uint256"},
            {"type": "uint80", "name": "answeredInRound", "internalType": "uint80"},
        ],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "setController",
        "inputs": [{"type": "address", "name": "_accessController", "internalType": "address"}],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "transferOwnership",
        "inputs": [{"type": "address", "name": "_to", "internalType": "address"}],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "version",
        "inputs": [],
        "outputs": [{"type": "uint256", "name": "", "internalType": "uint256"}],
        "stateMutability": "view",
    },
]
PRESALE_BLAST_ABI = [
    {
        "inputs": [
            {
                "internalType": "contract AggregatorV3Interface",
                "name": "COIN_PRICE_FEED_",
                "type": "address",
            },
            {"internalType": "contract IERC20", "name": "usdtToken_", "type": "address"},
            {"internalType": "contract IERC20", "name": "usdcToken_", "type": "address"},
            {"internalType": "contract IERC20", "name": "usdbToken_", "type": "address"},
            {"internalType": "contract IERC20", "name": "wethToken_", "type": "address"},
            {"internalType": "address", "name": "protocolWallet_", "type": "address"},
            {"internalType": "address", "name": "admin", "type": "address"},
        ],
        "stateMutability": "nonpayable",
        "type": "constructor",
    },
    {"inputs": [], "name": "EnforcedPause", "type": "error"},
    {"inputs": [], "name": "ExpectedPause", "type": "error"},
    {
        "inputs": [{"internalType": "address", "name": "owner", "type": "address"}],
        "name": "OwnableInvalidOwner",
        "type": "error",
    },
    {
        "inputs": [{"internalType": "address", "name": "account", "type": "address"}],
        "name": "OwnableUnauthorizedAccount",
        "type": "error",
    },
    {"inputs": [], "name": "SafeTransferFailed", "type": "error"},
    {"inputs": [], "name": "SafeTransferFromFailed", "type": "error"},
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "internalType": "address",
                "name": "previousOwner",
                "type": "address",
            },
            {"indexed": True, "internalType": "address", "name": "newOwner", "type": "address"},
        ],
        "name": "OwnershipTransferred",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "internalType": "address", "name": "account", "type": "address"}
        ],
        "name": "Paused",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "internalType": "uint256", "name": "currentStage", "type": "uint256"}
        ],
        "name": "StageUpdated",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "token", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "user", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "referrer", "type": "address"},
            {"indexed": False, "internalType": "uint256", "name": "amount", "type": "uint256"},
        ],
        "name": "TokensBought",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "internalType": "address", "name": "account", "type": "address"}
        ],
        "name": "Unpaused",
        "type": "event",
    },
    {
        "inputs": [],
        "name": "COIN_PRICE_FEED",
        "outputs": [
            {"internalType": "contract AggregatorV3Interface", "name": "", "type": "address"}
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "PRICEFEED_DECIMALS",
        "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "STABLETOKEN_PRICE",
        "outputs": [{"internalType": "int32", "name": "", "type": "int32"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "TOKEN_PRECISION",
        "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "user", "type": "address"}],
        "name": "balances",
        "outputs": [{"internalType": "uint256", "name": "balance", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "referrer", "type": "address"}],
        "name": "depositCoin",
        "outputs": [],
        "stateMutability": "payable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "address", "name": "referrer", "type": "address"},
        ],
        "name": "depositCoinTo",
        "outputs": [],
        "stateMutability": "payable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "address", "name": "referrer", "type": "address"},
        ],
        "name": "depositUSDB",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "address", "name": "referrer", "type": "address"},
        ],
        "name": "depositUSDBTo",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "address", "name": "referrer", "type": "address"},
        ],
        "name": "depositUSDC",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "address", "name": "referrer", "type": "address"},
        ],
        "name": "depositUSDCTo",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "address", "name": "referrer", "type": "address"},
        ],
        "name": "depositUSDT",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "address", "name": "referrer", "type": "address"},
        ],
        "name": "depositUSDTTo",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "address", "name": "referrer", "type": "address"},
        ],
        "name": "depositWETH",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "address", "name": "referrer", "type": "address"},
        ],
        "name": "depositWETHTo",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "owner",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "pause",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "paused",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "protocolWallet",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "renounceOwnership",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "contract IERC20", "name": "token", "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
        ],
        "name": "rescueFunds",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "stageIterator_", "type": "uint256"}],
        "name": "setStage",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "stageIterator",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "name": "stages",
        "outputs": [
            {"internalType": "uint96", "name": "cost", "type": "uint96"},
            {"internalType": "uint160", "name": "amount", "type": "uint160"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "totalSoldInUSD",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "totalTokensSold",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "newOwner", "type": "address"}],
        "name": "transferOwnership",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "unpause",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "wallet", "type": "address"}],
        "name": "updateProtocolWallet",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "amount", "type": "uint256"}],
        "name": "updateTotalSold",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "usdbToken",
        "outputs": [{"internalType": "contract IERC20", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "usdcToken",
        "outputs": [{"internalType": "contract IERC20", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "usdtToken",
        "outputs": [{"internalType": "contract IERC20", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "wethToken",
        "outputs": [{"internalType": "contract IERC20", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
]

LAUNCHPAD_CONTRACT_ADDRESS_ABI = [
    {
        "inputs": [
            {"internalType": "address", "name": "_weth", "type": "address"},
            {"internalType": "address", "name": "_usdb", "type": "address"},
            {"internalType": "address", "name": "_oracle", "type": "address"},
            {"internalType": "address", "name": "_yieldStaking", "type": "address"},
        ],
        "stateMutability": "nonpayable",
        "type": "constructor",
    },
    {
        "inputs": [{"internalType": "address", "name": "target", "type": "address"}],
        "name": "AddressEmptyCode",
        "type": "error",
    },
    {
        "inputs": [{"internalType": "address", "name": "account", "type": "address"}],
        "name": "AddressInsufficientBalance",
        "type": "error",
    },
    {"inputs": [], "name": "ECDSAInvalidSignature", "type": "error"},
    {
        "inputs": [{"internalType": "uint256", "name": "length", "type": "uint256"}],
        "name": "ECDSAInvalidSignatureLength",
        "type": "error",
    },
    {
        "inputs": [{"internalType": "bytes32", "name": "s", "type": "bytes32"}],
        "name": "ECDSAInvalidSignatureS",
        "type": "error",
    },
    {"inputs": [], "name": "FailedInnerCall", "type": "error"},
    {"inputs": [], "name": "InvalidInitialization", "type": "error"},
    {
        "inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}],
        "name": "InvalidSaleStatus",
        "type": "error",
    },
    {"inputs": [], "name": "NotInitializing", "type": "error"},
    {
        "inputs": [{"internalType": "address", "name": "owner", "type": "address"}],
        "name": "OwnableInvalidOwner",
        "type": "error",
    },
    {
        "inputs": [{"internalType": "address", "name": "account", "type": "address"}],
        "name": "OwnableUnauthorizedAccount",
        "type": "error",
    },
    {
        "inputs": [{"internalType": "address", "name": "token", "type": "address"}],
        "name": "SafeERC20FailedOperation",
        "type": "error",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "internalType": "uint64", "name": "version", "type": "uint64"}
        ],
        "name": "Initialized",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "internalType": "address",
                "name": "previousOwner",
                "type": "address",
            },
            {"indexed": True, "internalType": "address", "name": "newOwner", "type": "address"},
        ],
        "name": "OwnershipTransferred",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "token", "type": "address"},
            {"indexed": False, "internalType": "uint256", "name": "id", "type": "uint256"},
        ],
        "name": "TokenPlaced",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "token", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "buyer", "type": "address"},
            {"indexed": False, "internalType": "uint256", "name": "id", "type": "uint256"},
            {"indexed": False, "internalType": "uint256", "name": "amount", "type": "uint256"},
        ],
        "name": "TokensBought",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "token", "type": "address"},
            {"indexed": False, "internalType": "uint256", "name": "id", "type": "uint256"},
            {"indexed": False, "internalType": "address", "name": "user", "type": "address"},
        ],
        "name": "TokensClaimed",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "user", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "token", "type": "address"},
            {"indexed": False, "internalType": "uint256", "name": "id", "type": "uint256"},
            {
                "indexed": False,
                "internalType": "enum LaunchpadDataTypes.UserTiers",
                "name": "tier",
                "type": "uint8",
            },
        ],
        "name": "UserRegistered",
        "type": "event",
    },
    {
        "inputs": [],
        "name": "USDB",
        "outputs": [{"internalType": "contract IERC20", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "WETH",
        "outputs": [{"internalType": "contract IERC20", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "address", "name": "paymentContract", "type": "address"},
            {"internalType": "uint256", "name": "volume", "type": "uint256"},
            {"internalType": "address", "name": "receiver", "type": "address"},
            {"internalType": "bytes", "name": "signature", "type": "bytes"},
        ],
        "name": "buyTokens",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "payable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}],
        "name": "claimRemainders",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}],
        "name": "claimTokens",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "decimalsUSDB",
        "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "address", "name": "user", "type": "address"},
        ],
        "name": "getClaimableAmount",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}],
        "name": "getPlacedToken",
        "outputs": [
            {
                "components": [
                    {"internalType": "uint256", "name": "price", "type": "uint256"},
                    {"internalType": "uint256", "name": "volumeForYieldStakers", "type": "uint256"},
                    {"internalType": "uint256", "name": "volume", "type": "uint256"},
                    {
                        "internalType": "uint256",
                        "name": "initialVolumeForLowTiers",
                        "type": "uint256",
                    },
                    {
                        "internalType": "uint256",
                        "name": "initialVolumeForHighTiers",
                        "type": "uint256",
                    },
                    {"internalType": "uint256", "name": "lowTiersWeightsSum", "type": "uint256"},
                    {"internalType": "uint256", "name": "highTiersWeightsSum", "type": "uint256"},
                    {"internalType": "address", "name": "addressForCollected", "type": "address"},
                    {"internalType": "uint256", "name": "registrationStart", "type": "uint256"},
                    {"internalType": "uint256", "name": "registrationEnd", "type": "uint256"},
                    {"internalType": "uint256", "name": "publicSaleStart", "type": "uint256"},
                    {"internalType": "uint256", "name": "fcfsSaleStart", "type": "uint256"},
                    {"internalType": "uint256", "name": "saleEnd", "type": "uint256"},
                    {"internalType": "uint256", "name": "tgeStart", "type": "uint256"},
                    {"internalType": "uint256", "name": "vestingStart", "type": "uint256"},
                    {"internalType": "uint256", "name": "vestingDuration", "type": "uint256"},
                    {"internalType": "uint8", "name": "tokenDecimals", "type": "uint8"},
                    {"internalType": "uint8", "name": "tgePercent", "type": "uint8"},
                    {"internalType": "bool", "name": "approved", "type": "bool"},
                    {"internalType": "address", "name": "token", "type": "address"},
                ],
                "internalType": "struct LaunchpadDataTypes.PlacedToken",
                "name": "",
                "type": "tuple",
            }
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}],
        "name": "getStatus",
        "outputs": [
            {"internalType": "enum LaunchpadDataTypes.SaleStatus", "name": "", "type": "uint8"}
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "_owner", "type": "address"},
            {"internalType": "address", "name": "_signer", "type": "address"},
            {"internalType": "address", "name": "_operator", "type": "address"},
            {"internalType": "address", "name": "_points", "type": "address"},
            {"internalType": "address", "name": "_pointsOperator", "type": "address"},
        ],
        "name": "initialize",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "enum LaunchpadDataTypes.UserTiers", "name": "", "type": "uint8"}
        ],
        "name": "minAmountForTier",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "operator",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "oracle",
        "outputs": [{"internalType": "contract IChainlinkOracle", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "oracleDecimals",
        "outputs": [{"internalType": "uint8", "name": "", "type": "uint8"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "owner",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {
                "components": [
                    {"internalType": "uint256", "name": "price", "type": "uint256"},
                    {"internalType": "uint256", "name": "volumeForYieldStakers", "type": "uint256"},
                    {"internalType": "uint256", "name": "volume", "type": "uint256"},
                    {
                        "internalType": "uint256",
                        "name": "initialVolumeForLowTiers",
                        "type": "uint256",
                    },
                    {
                        "internalType": "uint256",
                        "name": "initialVolumeForHighTiers",
                        "type": "uint256",
                    },
                    {"internalType": "uint256", "name": "lowTiersWeightsSum", "type": "uint256"},
                    {"internalType": "uint256", "name": "highTiersWeightsSum", "type": "uint256"},
                    {"internalType": "address", "name": "addressForCollected", "type": "address"},
                    {"internalType": "uint256", "name": "registrationStart", "type": "uint256"},
                    {"internalType": "uint256", "name": "registrationEnd", "type": "uint256"},
                    {"internalType": "uint256", "name": "publicSaleStart", "type": "uint256"},
                    {"internalType": "uint256", "name": "fcfsSaleStart", "type": "uint256"},
                    {"internalType": "uint256", "name": "saleEnd", "type": "uint256"},
                    {"internalType": "uint256", "name": "tgeStart", "type": "uint256"},
                    {"internalType": "uint256", "name": "vestingStart", "type": "uint256"},
                    {"internalType": "uint256", "name": "vestingDuration", "type": "uint256"},
                    {"internalType": "uint8", "name": "tokenDecimals", "type": "uint8"},
                    {"internalType": "uint8", "name": "tgePercent", "type": "uint8"},
                    {"internalType": "bool", "name": "approved", "type": "bool"},
                    {"internalType": "address", "name": "token", "type": "address"},
                ],
                "internalType": "struct LaunchpadDataTypes.PlacedToken",
                "name": "_placedToken",
                "type": "tuple",
            }
        ],
        "name": "placeTokens",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "name": "placedTokens",
        "outputs": [
            {"internalType": "uint256", "name": "price", "type": "uint256"},
            {"internalType": "uint256", "name": "volumeForYieldStakers", "type": "uint256"},
            {"internalType": "uint256", "name": "volume", "type": "uint256"},
            {"internalType": "uint256", "name": "initialVolumeForLowTiers", "type": "uint256"},
            {"internalType": "uint256", "name": "initialVolumeForHighTiers", "type": "uint256"},
            {"internalType": "uint256", "name": "lowTiersWeightsSum", "type": "uint256"},
            {"internalType": "uint256", "name": "highTiersWeightsSum", "type": "uint256"},
            {"internalType": "address", "name": "addressForCollected", "type": "address"},
            {"internalType": "uint256", "name": "registrationStart", "type": "uint256"},
            {"internalType": "uint256", "name": "registrationEnd", "type": "uint256"},
            {"internalType": "uint256", "name": "publicSaleStart", "type": "uint256"},
            {"internalType": "uint256", "name": "fcfsSaleStart", "type": "uint256"},
            {"internalType": "uint256", "name": "saleEnd", "type": "uint256"},
            {"internalType": "uint256", "name": "tgeStart", "type": "uint256"},
            {"internalType": "uint256", "name": "vestingStart", "type": "uint256"},
            {"internalType": "uint256", "name": "vestingDuration", "type": "uint256"},
            {"internalType": "uint8", "name": "tokenDecimals", "type": "uint8"},
            {"internalType": "uint8", "name": "tgePercent", "type": "uint8"},
            {"internalType": "bool", "name": "approved", "type": "bool"},
            {"internalType": "address", "name": "token", "type": "address"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "enum LaunchpadDataTypes.UserTiers", "name": "tier", "type": "uint8"},
            {"internalType": "uint256", "name": "amountOfTokens", "type": "uint256"},
            {"internalType": "bytes", "name": "signature", "type": "bytes"},
        ],
        "name": "register",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "enum LaunchpadDataTypes.UserTiers", "name": "tier", "type": "uint8"},
            {"internalType": "uint256", "name": "amountOfTokens", "type": "uint256"},
            {"internalType": "bytes", "name": "signature", "type": "bytes"},
            {"internalType": "bytes", "name": "approveSignature", "type": "bytes"},
        ],
        "name": "registerWithApprove",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "renounceOwnership",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "uint256", "name": "_fcfsSaleStart", "type": "uint256"},
        ],
        "name": "setFCFSSaleStart",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256[6]", "name": "amounts", "type": "uint256[6]"}],
        "name": "setMinAmountsForTiers",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "_operator", "type": "address"}],
        "name": "setOperator",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "uint256", "name": "_publicSaleStart", "type": "uint256"},
        ],
        "name": "setPublicSaleStart",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "uint256", "name": "_registrationEnd", "type": "uint256"},
        ],
        "name": "setRegistrationEnd",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "uint256", "name": "_registrationStart", "type": "uint256"},
        ],
        "name": "setRegistrationStart",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "uint256", "name": "_saleEnd", "type": "uint256"},
        ],
        "name": "setSaleEnd",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "_signer", "type": "address"}],
        "name": "setSigner",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "uint256", "name": "_tgeStart", "type": "uint256"},
        ],
        "name": "setTgeStart",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "uint256", "name": "_vestingStart", "type": "uint256"},
        ],
        "name": "setVestingStart",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256[6]", "name": "weights", "type": "uint256[6]"}],
        "name": "setWeightsForTiers",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "signer",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "newOwner", "type": "address"}],
        "name": "transferOwnership",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "address", "name": "user", "type": "address"},
        ],
        "name": "userAllowedAllocation",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "id", "type": "uint256"},
            {"internalType": "address", "name": "user", "type": "address"},
        ],
        "name": "userInfo",
        "outputs": [
            {
                "components": [
                    {"internalType": "uint256", "name": "claimedAmount", "type": "uint256"},
                    {"internalType": "uint256", "name": "boughtAmount", "type": "uint256"},
                    {"internalType": "uint256", "name": "boughtPublicSale", "type": "uint256"},
                    {
                        "internalType": "enum LaunchpadDataTypes.UserTiers",
                        "name": "tier",
                        "type": "uint8",
                    },
                    {"internalType": "bool", "name": "registered", "type": "bool"},
                ],
                "internalType": "struct LaunchpadDataTypes.User",
                "name": "",
                "type": "tuple",
            }
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "", "type": "uint256"},
            {"internalType": "address", "name": "", "type": "address"},
        ],
        "name": "users",
        "outputs": [
            {"internalType": "uint256", "name": "claimedAmount", "type": "uint256"},
            {"internalType": "uint256", "name": "boughtAmount", "type": "uint256"},
            {"internalType": "uint256", "name": "boughtPublicSale", "type": "uint256"},
            {"internalType": "enum LaunchpadDataTypes.UserTiers", "name": "tier", "type": "uint8"},
            {"internalType": "bool", "name": "registered", "type": "bool"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "enum LaunchpadDataTypes.UserTiers", "name": "", "type": "uint8"}
        ],
        "name": "weightForTier",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "yieldStaking",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
]

LAUNCHPAD_PLACE_TOKENS_ABI = {
    "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
    "name": "placedTokens",
    "outputs": [
        {"internalType": "uint256", "name": "price", "type": "uint256"},
        {"internalType": "uint256", "name": "volumeForYieldStakers", "type": "uint256"},
        {"internalType": "uint256", "name": "volume", "type": "uint256"},
        {"internalType": "uint256", "name": "initialVolumeForLowTiers", "type": "uint256"},
        {"internalType": "uint256", "name": "initialVolumeForHighTiers", "type": "uint256"},
        {"internalType": "uint256", "name": "lowTiersWeightsSum", "type": "uint256"},
        {"internalType": "uint256", "name": "highTiersWeightsSum", "type": "uint256"},
        {"internalType": "address", "name": "addressForCollected", "type": "address"},
        {"internalType": "uint256", "name": "registrationStart", "type": "uint256"},
        {"internalType": "uint256", "name": "registrationEnd", "type": "uint256"},
        {"internalType": "uint256", "name": "publicSaleStart", "type": "uint256"},
        {"internalType": "uint256", "name": "fcfsSaleStart", "type": "uint256"},
        {"internalType": "uint256", "name": "saleEnd", "type": "uint256"},
        {"internalType": "uint256", "name": "tgeStart", "type": "uint256"},
        {"internalType": "uint256", "name": "vestingStart", "type": "uint256"},
        {"internalType": "uint256", "name": "vestingDuration", "type": "uint256"},
        {"internalType": "uint8", "name": "tokenDecimals", "type": "uint8"},
        {"internalType": "uint8", "name": "tgePercent", "type": "uint8"},
        {"internalType": "bool", "name": "approved", "type": "bool"},
        {"internalType": "address", "name": "token", "type": "address"},
    ],
    "stateMutability": "view",
    "type": "function",
}
TRY_AGGREGATE_ABI = {
    "inputs": [
        {"name": "requireSuccess", "type": "bool"},
        {
            "components": [
                {"name": "target", "type": "address"},
                {"name": "callData", "type": "bytes"},
            ],
            "name": "calls",
            "type": "tuple[]",
        },
    ],
    "name": "tryAggregate",
    "outputs": [
        {
            "components": [
                {"name": "success", "type": "bool"},
                {"name": "returnData", "type": "bytes"},
            ],
            "name": "returnData",
            "type": "tuple[]",
        }
    ],
    "stateMutability": "nonpayable",
    "type": "function",
}
