from os import getenv

from dotenv import load_dotenv

load_dotenv()

APP_ENV = getenv("APP_ENV", "dev")
APP_VERSION = getenv("APP_VERSION", "unstable")

SENTRY_DSN = getenv("SENTRY_DSN", None)
LOGTAIL_TOKEN = getenv("LOGTAIL_TOKEN")

ALLOWED_ORIGINS = getenv("ALLOWED_ORIGINS", "*").split(",")

DATABASE_URL = getenv("DATABASE_URL", "postgresql+asyncpg://blastup:blastup@postgres:5432/blastup")
REDIS_URL = getenv("REDIS_URL", "redis://localhost:6379")
CELERY_BROKER = getenv("CELERY_BROKER", "redis://localhost:6379/0")
CELERY_RETRY_AFTER = int(getenv("CELERY_RETRY_AFTER", "15"))

CONTROLLER_SEED_PHRASE = getenv("CONTROLLER_SEED_PHRASE")

IDO_SIGN_ACCOUNT_PRIVATE_KEY = getenv("IDO_SIGN_ACCOUNT_PRIVATE_KEY")
LAUNCHPAD_CONTRACT_ADDRESS = getenv("LAUNCHPAD_CONTRACT_ADDRESS")

COINGECKO_API_KEY = getenv("COINGECKO_API_KEY")

# ONRAMP ONLY
ETH_PRICE_FEED_ADDR = getenv("ETH_PRICE_FEED_ADDR")

MUNZEN_ENVIRONMENT = getenv("MUNZEN_ENVIRONMENT", "sandbox")
MUNZEN_API_KEY = getenv("MUNZEN_API_KEY", "")
MUNZEN_API_SECRET = getenv("MUNZEN_API_SECRET", "")

ONRAMP_RECIPIENT_ADDR = getenv("ONRAMP_RECIPIENT_ADDR")
ONRAMP_SEED_PHRASE = getenv("ONRAMP_SEED_PHRASE", "")
ONRAMP_SENDER_ADDR = getenv("ONRAMP_SENDER_ADDR")
ONRAMP_SENDER_SEED_PHRASE = getenv("ONRAMP_SENDER_SEED_PHRASE")
# ONRAMP ONLY

USDT_CONTRACT_ADDR_ETH = getenv("USDT_CONTRACT_ADDR_ETH")
USDT_CONTRACT_ADDR_BSC = getenv("USDT_CONTRACT_ADDR_BSC")
USDT_CONTRACT_ADDR_POLYGON = getenv("USDT_CONTRACT_ADDR_POLYGON")
USDT_CONTRACT_ADDR_BLAST = getenv("USDT_CONTRACT_ADDR_BLAST")

CRYPTO_ENVIRONMENT = getenv("CRYPTO_ENVIRONMENT", "testnet")
CRYPTO_API_KEY_ETH = getenv("CRYPTO_API_KEY_ETH", "")
CRYPTO_API_KEY_POLYGON = getenv("CRYPTO_API_KEY_POLYGON", "")
CRYPTO_API_KEY_BSC = getenv("CRYPTO_API_KEY_BSC", "")
CRYPTO_API_KEY_BLAST = getenv("CRYPTO_API_KEY_BLAST")
FALLBACK_API_URL_ETH = getenv("FALLBACK_API_URL_ETH")
FALLBACK_API_URL_POLYGON = getenv("FALLBACK_APY_URL_POLYGON")
FALLBACK_API_URL_BSC = getenv("FALLBACK_APY_URL_BSC")
FALLBACK_API_URL_BLAST = getenv("FALLBACK_APY_URL_BSC")
FALLBACK_API_KEY_ETH = getenv("NODIES_API_KEY_ETH")
FALLBACK_API_KEY_POLYGON = getenv("NODIES_API_KEY_POLYGON")
FALLBACK_API_KEY_BSC = getenv("NODIES_API_KEY_BSC")
FALLBACK_API_KEY_BLAST = getenv("NODIES_API_KEY_BLAST")

CONTRACT_ADDR_ETH = getenv("CONTRACT_ADDR_ETH")
CONTRACT_ADDR_POLYGON = getenv("CONTRACT_ADDR_POLYGON")
CONTRACT_ADDR_BSC = getenv("CONTRACT_ADDR_BSC")
CONTRACT_ADDR_BLAST = getenv("CONTRACT_ADDR_BLAST")

ADMIN_USERNAME = getenv("ADMIN_USERNAME")
ADMIN_PASSWORD = getenv("ADMIN_PASSWORD")

SECRET_KEY = getenv("SECRET_KEY")
ALGORITHM = getenv("ALGORITHM")
TOKEN_EXPIRATION = getenv("TOKEN_EXPIRATION")

_log_level = getenv("LOG_LEVEL", "DEBUG")
if _log_level not in ("CRITICAL", "FATAL", "ERROR", "WARNING", "INFO", "DEBUG"):
    _log_level = "INFO"

LOG_LEVEL = _log_level
