PRICE_FEED_ABI = [{"type": "constructor", "name": "",
                   "inputs": [{"type": "address", "name": "_aggregator", "internalType": "address"},
                              {"type": "address", "name": "_accessController", "internalType": "address"}],
                   "outputs": [], "stateMutability": "nonpayable"}, {"type": "event", "name": "AnswerUpdated",
                                                                     "inputs": [{"type": "int256", "name": "current",
                                                                                 "indexed": True,
                                                                                 "internalType": "int256"},
                                                                                {"type": "uint256", "name": "roundId",
                                                                                 "indexed": True,
                                                                                 "internalType": "uint256"},
                                                                                {"type": "uint256", "name": "updatedAt",
                                                                                 "indexed": False,
                                                                                 "internalType": "uint256"}],
                                                                     "outputs": [], "anonymous": False},
                  {"type": "event", "name": "NewRound",
                   "inputs": [{"type": "uint256", "name": "roundId", "indexed": True, "internalType": "uint256"},
                              {"type": "address", "name": "startedBy", "indexed": True, "internalType": "address"},
                              {"type": "uint256", "name": "startedAt", "indexed": False, "internalType": "uint256"}],
                   "outputs": [], "anonymous": False}, {"type": "event", "name": "OwnershipTransferRequested",
                                                        "inputs": [{"type": "address", "name": "from", "indexed": True,
                                                                    "internalType": "address"},
                                                                   {"type": "address", "name": "to", "indexed": True,
                                                                    "internalType": "address"}], "outputs": [],
                                                        "anonymous": False},
                  {"type": "event", "name": "OwnershipTransferred",
                   "inputs": [{"type": "address", "name": "from", "indexed": True, "internalType": "address"},
                              {"type": "address", "name": "to", "indexed": True, "internalType": "address"}],
                   "outputs": [], "anonymous": False},
                  {"type": "function", "name": "acceptOwnership", "inputs": [], "outputs": [],
                   "stateMutability": "nonpayable"}, {"type": "function", "name": "accessController", "inputs": [],
                                                      "outputs": [{"type": "address", "name": "",
                                                                   "internalType": "contract AccessControllerInterface"}],
                                                      "stateMutability": "view"},
                  {"type": "function", "name": "aggregator", "inputs": [],
                   "outputs": [{"type": "address", "name": "", "internalType": "address"}], "stateMutability": "view"},
                  {"type": "function", "name": "confirmAggregator",
                   "inputs": [{"type": "address", "name": "_aggregator", "internalType": "address"}], "outputs": [],
                   "stateMutability": "nonpayable"}, {"type": "function", "name": "decimals", "inputs": [], "outputs": [
        {"type": "uint8", "name": "", "internalType": "uint8"}], "stateMutability": "view"},
                  {"type": "function", "name": "description", "inputs": [],
                   "outputs": [{"type": "string", "name": "", "internalType": "string"}], "stateMutability": "view"},
                  {"type": "function", "name": "getAnswer",
                   "inputs": [{"type": "uint256", "name": "_roundId", "internalType": "uint256"}],
                   "outputs": [{"type": "int256", "name": "", "internalType": "int256"}], "stateMutability": "view"},
                  {"type": "function", "name": "getRoundData",
                   "inputs": [{"type": "uint80", "name": "_roundId", "internalType": "uint80"}],
                   "outputs": [{"type": "uint80", "name": "roundId", "internalType": "uint80"},
                               {"type": "int256", "name": "answer", "internalType": "int256"},
                               {"type": "uint256", "name": "startedAt", "internalType": "uint256"},
                               {"type": "uint256", "name": "updatedAt", "internalType": "uint256"},
                               {"type": "uint80", "name": "answeredInRound", "internalType": "uint80"}],
                   "stateMutability": "view"}, {"type": "function", "name": "getTimestamp", "inputs": [
        {"type": "uint256", "name": "_roundId", "internalType": "uint256"}],
                                                "outputs": [{"type": "uint256", "name": "", "internalType": "uint256"}],
                                                "stateMutability": "view"},
                  {"type": "function", "name": "latestAnswer", "inputs": [],
                   "outputs": [{"type": "int256", "name": "", "internalType": "int256"}], "stateMutability": "view"},
                  {"type": "function", "name": "latestRound", "inputs": [],
                   "outputs": [{"type": "uint256", "name": "", "internalType": "uint256"}], "stateMutability": "view"},
                  {"type": "function", "name": "latestRoundData", "inputs": [],
                   "outputs": [{"type": "uint80", "name": "roundId", "internalType": "uint80"},
                               {"type": "int256", "name": "answer", "internalType": "int256"},
                               {"type": "uint256", "name": "startedAt", "internalType": "uint256"},
                               {"type": "uint256", "name": "updatedAt", "internalType": "uint256"},
                               {"type": "uint80", "name": "answeredInRound", "internalType": "uint80"}],
                   "stateMutability": "view"}, {"type": "function", "name": "latestTimestamp", "inputs": [],
                                                "outputs": [{"type": "uint256", "name": "", "internalType": "uint256"}],
                                                "stateMutability": "view"},
                  {"type": "function", "name": "owner", "inputs": [],
                   "outputs": [{"type": "address", "name": "", "internalType": "address payable"}],
                   "stateMutability": "view"}, {"type": "function", "name": "phaseAggregators",
                                                "inputs": [{"type": "uint16", "name": "", "internalType": "uint16"}],
                                                "outputs": [{"type": "address", "name": "",
                                                             "internalType": "contract AggregatorV2V3Interface"}],
                                                "stateMutability": "view"},
                  {"type": "function", "name": "phaseId", "inputs": [],
                   "outputs": [{"type": "uint16", "name": "", "internalType": "uint16"}], "stateMutability": "view"},
                  {"type": "function", "name": "proposeAggregator",
                   "inputs": [{"type": "address", "name": "_aggregator", "internalType": "address"}], "outputs": [],
                   "stateMutability": "nonpayable"}, {"type": "function", "name": "proposedAggregator", "inputs": [],
                                                      "outputs": [{"type": "address", "name": "",
                                                                   "internalType": "contract AggregatorV2V3Interface"}],
                                                      "stateMutability": "view"},
                  {"type": "function", "name": "proposedGetRoundData",
                   "inputs": [{"type": "uint80", "name": "_roundId", "internalType": "uint80"}],
                   "outputs": [{"type": "uint80", "name": "roundId", "internalType": "uint80"},
                               {"type": "int256", "name": "answer", "internalType": "int256"},
                               {"type": "uint256", "name": "startedAt", "internalType": "uint256"},
                               {"type": "uint256", "name": "updatedAt", "internalType": "uint256"},
                               {"type": "uint80", "name": "answeredInRound", "internalType": "uint80"}],
                   "stateMutability": "view"}, {"type": "function", "name": "proposedLatestRoundData", "inputs": [],
                                                "outputs": [
                                                    {"type": "uint80", "name": "roundId", "internalType": "uint80"},
                                                    {"type": "int256", "name": "answer", "internalType": "int256"},
                                                    {"type": "uint256", "name": "startedAt", "internalType": "uint256"},
                                                    {"type": "uint256", "name": "updatedAt", "internalType": "uint256"},
                                                    {"type": "uint80", "name": "answeredInRound",
                                                     "internalType": "uint80"}], "stateMutability": "view"},
                  {"type": "function", "name": "setController",
                   "inputs": [{"type": "address", "name": "_accessController", "internalType": "address"}],
                   "outputs": [], "stateMutability": "nonpayable"}, {"type": "function", "name": "transferOwnership",
                                                                     "inputs": [{"type": "address", "name": "_to",
                                                                                 "internalType": "address"}],
                                                                     "outputs": [], "stateMutability": "nonpayable"},
                  {"type": "function", "name": "version", "inputs": [],
                   "outputs": [{"type": "uint256", "name": "", "internalType": "uint256"}], "stateMutability": "view"}]