"""auto

Revision ID: ba560db8cb95
Revises: 17aab55a6772
Create Date: 2024-04-04 11:53:49.793051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba560db8cb95'
down_revision: Union[str, None] = '17aab55a6772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('launchpad_project', sa.Column('is_active', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('token_details', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_details', 'icon')
    op.drop_column('launchpad_project', 'is_active')
    # ### end Alembic commands ###
