"""approve_for_reg is_required flag

Revision ID: 5a83883bba79
Revises: fd4cc4ad60b2
Create Date: 2024-05-02 11:47:13.747668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a83883bba79'
down_revision: Union[str, None] = '62d67d8d01c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('launchpad_project', sa.Column('approve_for_registration_is_required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('launchpad_project', 'approve_for_registration_is_required')
    # ### end Alembic commands ###
