"""rm badge type trigger

Revision ID: 385bcfdd8e29
Revises: 4fea8e76dcf3
Create Date: 2024-05-11 11:40:26.589647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385bcfdd8e29'
down_revision: Union[str, None] = '4fea8e76dcf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION IF EXISTS check_badges_type(varchar);")
    op.execute("DROP FUNCTION IF EXISTS check_badges_trigger CASCADE;")
    op.execute("DROP TRIGGER IF EXISTS check_badges_type_trigger ON launchpad_project;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
