"""referring_profile_id and ido_farming reasons

Revision ID: 98c3e5267e08
Revises: e1c9edea5a23
Create Date: 2024-06-06 12:19:43.581095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98c3e5267e08'
down_revision: Union[str, None] = '1753b23ed0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE operationreason ADD VALUE 'IDO_FARMING';")
    op.add_column('points_history', sa.Column('referring_profile_id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=True))
    op.create_foreign_key("points_history_referring_profile_id_fkey",  'points_history',  'profiles',  ['referring_profile_id'],  ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("points_history_referring_profile_id_fkey", 'points_history', type_='foreignkey')
    op.drop_column('points_history', 'referring_profile_id')
    # ### end Alembic commands ###
