"""empty message

Revision ID: 521d7a215689
Revises: 509b65d48099
Create Date: 2024-04-11 18:20:12.449303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521d7a215689'
down_revision: Union[str, None] = '509b65d48099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_image', sa.Column('ordering_key', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_project_image_ordering_key'), 'project_image', ['ordering_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_image_ordering_key'), table_name='project_image')
    op.drop_column('project_image', 'ordering_key')
    # ### end Alembic commands ###
