"""auto

Revision ID: a03de7029125
Revises: 
Create Date: 2024-04-02 12:04:26.909886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03de7029125'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launchpad_project',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('token_sale_details', sa.Text(), nullable=True),
    sa.Column('total_raise', sa.DECIMAL(), nullable=True),
    sa.Column('token_price', sa.DECIMAL(), nullable=False),
    sa.Column('project_type', sa.Enum('DEFAULT', 'PARTNERSHIP_PRESALE', name='projecttype'), nullable=True),
    sa.Column('registration_start_at', sa.DateTime(), nullable=False),
    sa.Column('registration_end_at', sa.DateTime(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('fcfs_opens_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('onramp_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('hash', sa.Text(), nullable=True),
    sa.Column('amount', sa.Text(), nullable=False),
    sa.Column('received_amount', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='new', nullable=True),
    sa.Column('extra', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_onramp_order_address'), 'onramp_order', ['address'], unique=False)
    op.create_table('project_image',
    sa.Column('id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['launchpad_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_link',
    sa.Column('id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('DEFAULT', 'TWITTER', 'DISCORD', 'TELEGRAM', name='projectlinktype'), server_default='DEFAULT', nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['launchpad_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxy_link',
    sa.Column('id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['launchpad_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proxy_link')
    op.drop_table('project_link')
    op.drop_table('project_image')
    op.drop_index(op.f('ix_onramp_order_address'), table_name='onramp_order')
    op.drop_table('onramp_order')
    op.drop_table('launchpad_project')
    # ### end Alembic commands ###
