"""adds fields to profile

Revision ID: 7f9330cf25b5
Revises: 0822cc2cd3fc
Create Date: 2024-06-05 11:07:59.898968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f9330cf25b5'
down_revision: Union[str, None] = '0822cc2cd3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('utm', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('language', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('first_login', sa.DateTime(), nullable=True))
    op.add_column('profiles', sa.Column('ip', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('browser', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('device_resolution', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('device_type', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('browser_referrer', sa.Text(), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'browser_referrer')
    op.drop_column('profiles', 'device_type')
    op.drop_column('profiles', 'device_resolution')
    op.drop_column('profiles', 'browser')
    op.drop_column('profiles', 'ip')
    op.drop_column('profiles', 'first_login')
    op.drop_column('profiles', 'language')
    op.drop_column('profiles', 'utm')
    # ### end Alembic commands ###
