"""auto

Revision ID: 1308fc4fe056
Revises: 1d0fe7ddf14b
Create Date: 2024-04-02 12:39:23.516691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1308fc4fe056'
down_revision: Union[str, None] = '1d0fe7ddf14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_link',
    sa.Column('id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_onramp_orders_address', table_name='onramp_order')
    op.create_index(op.f('ix_onramp_order_address'), 'onramp_order', ['address'], unique=False)
    op.drop_constraint('project_image_project_id_fkey', 'project_image', type_='foreignkey')
    op.drop_column('project_image', 'project_id')
    op.drop_constraint('project_link_project_id_fkey', 'project_link', type_='foreignkey')
    op.drop_column('project_link', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_link', sa.Column('project_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('project_link_project_id_fkey', 'project_link', 'launchpad_project', ['project_id'], ['id'])
    op.add_column('project_image', sa.Column('project_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('project_image_project_id_fkey', 'project_image', 'launchpad_project', ['project_id'], ['id'])
    op.drop_index(op.f('ix_onramp_order_address'), table_name='onramp_order')
    op.create_index('ix_onramp_orders_address', 'onramp_order', ['address'], unique=False)
    op.drop_table('proxy_link')
    # ### end Alembic commands ###
