"""add refcodes and referal info

Revision ID: b7dda864b901
Revises: 0dec9901fae0
Create Date: 2024-06-03 18:15:43.195171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7dda864b901'
down_revision: Union[str, None] = '0dec9901fae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refcodes',
    sa.Column('id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('refcode', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refcodes_address'), 'refcodes', ['address'], unique=False)
    op.create_index(op.f('ix_refcodes_refcode'), 'refcodes', ['refcode'], unique=False)
    op.add_column('tmp_profiles', sa.Column('referrer', sa.Text(), nullable=True))
    op.add_column('tmp_profiles', sa.Column('ref_points', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), server_default=sa.text('0::bigint'), nullable=True))
    op.add_column('tmp_profiles', sa.Column('ref_percent', sa.Integer(), server_default=sa.text('20::int'), nullable=True))
    op.add_column('tmp_profiles', sa.Column('ref_bonus_used', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_tmp_profiles_referrer'), 'tmp_profiles', ['referrer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tmp_profiles_referrer'), table_name='tmp_profiles')
    op.drop_column('tmp_profiles', 'ref_bonus_used')
    op.drop_column('tmp_profiles', 'ref_percent')
    op.drop_column('tmp_profiles', 'ref_points')
    op.drop_column('tmp_profiles', 'referrer')
    op.drop_index(op.f('ix_refcodes_refcode'), table_name='refcodes')
    op.drop_index(op.f('ix_refcodes_address'), table_name='refcodes')
    op.drop_table('refcodes')
    # ### end Alembic commands ###
