"""add launchpad contract events

Revision ID: edd95b89a2d9
Revises: 385bcfdd8e29
Create Date: 2024-05-12 21:11:56.649253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd95b89a2d9'
down_revision: Union[str, None] = '385bcfdd8e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launchpad_contract_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('event_type', sa.Enum('TOKENS_BOUGHT', 'USER_REGISTERED', name='launchpadcontracteventtype'), nullable=False),
    sa.Column('user_address', sa.String(), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('contract_project_id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('extra', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=True),
    sa.Column('txn_hash', sa.String(), nullable=False),
    sa.Column('block_number', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txn_hash')
    )
    op.create_index(op.f('ix_launchpad_contract_events_user_address'), 'launchpad_contract_events', ['user_address'], unique=False)
    op.create_unique_constraint("ux_launchpad_contract_events_txn_hash", 'launchpad_contract_events', ['txn_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ux_launchpad_contract_events_txn_hash", 'launchpad_contract_events', type_='unique')
    op.drop_index(op.f('ix_launchpad_contract_events_user_address'), table_name='launchpad_contract_events')
    op.drop_table('launchpad_contract_events')
    op.execute("DROP TYPE launchpadcontracteventtype")
    # ### end Alembic commands ###
