"""change history stake amount type

Revision ID: 62d67d8d01c9
Revises: fd4cc4ad60b2
Create Date: 2024-05-02 14:34:47.277211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d67d8d01c9'
down_revision: Union[str, None] = 'fd4cc4ad60b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. create new column with type TEXT
    op.add_column('stake_history', sa.Column('new_amount', sa.Text()))

    # 2. copy data from old column to new column
    op.execute("UPDATE stake_history SET new_amount = amount::text")

    # 3. delete old column
    op.drop_column('stake_history', 'amount')

    # 4. rename new column
    op.alter_column('stake_history', 'new_amount', new_column_name='amount')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. create new column with type TEXT
    op.add_column('stake_history', sa.Column('new_amount', sa.BIGINT()))

    # 2. copy data from old column to new column
    op.execute("UPDATE stake_history SET new_amount = amount::bigint")

    # 3. delete old column
    op.drop_column('stake_history', 'amount')

    # 4. rename new column
    op.alter_column('stake_history', 'new_amount', new_column_name='amount')

    # ### end Alembic commands ###
