"""tge_full_date

Revision ID: bfd073a9ee5f
Revises: 257075b44257
Create Date: 2024-05-24 12:19:51.324829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd073a9ee5f'
down_revision: Union[str, None] = '257075b44257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_details', sa.Column('tge_full_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_details', 'tge_full_date')
    # ### end Alembic commands ###
