"""auto

Revision ID: c4318467f675
Revises: 4d4d74d067de
Create Date: 2024-03-29 15:49:42.124461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4318467f675'
down_revision: Union[str, None] = '4d4d74d067de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('launchpad_project', sa.Column('slug', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'launchpad_project', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'launchpad_project', type_='unique')
    op.drop_column('launchpad_project', 'slug')
    # ### end Alembic commands ###
