"""add munzen txn_hash

Revision ID: 4fea8e76dcf3
Revises: 21cd7c36589a
Create Date: 2024-05-07 18:13:58.486372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fea8e76dcf3'
down_revision: Union[str, None] = 'fbd5b5ddb82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onramp_order', sa.Column('munzen_txn_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onramp_order', 'munzen_txn_hash')
    # ### end Alembic commands ###
