"""is_clickable

Revision ID: e522a9d71eb9
Revises: b71fb4f1c1cf
Create Date: 2024-06-24 17:15:48.548599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e522a9d71eb9'
down_revision: Union[str, None] = 'b71fb4f1c1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('launchpad_project', sa.Column('is_clickable', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('launchpad_project', 'is_clickable')
    # ### end Alembic commands ###
