"""auto

Revision ID: 08723b294879
Revises: 72e3bbb4def9
Create Date: 2024-04-02 12:42:09.556994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08723b294879'
down_revision: Union[str, None] = '72e3bbb4def9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_image', sa.Column('project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'project_image', 'launchpad_project', ['project_id'], ['id'])
    op.add_column('project_link', sa.Column('project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'project_link', 'launchpad_project', ['project_id'], ['id'])
    op.add_column('proxy_link', sa.Column('project_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'proxy_link', 'launchpad_project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proxy_link', type_='foreignkey')
    op.drop_column('proxy_link', 'project_id')
    op.drop_constraint(None, 'project_link', type_='foreignkey')
    op.drop_column('project_link', 'project_id')
    op.drop_constraint(None, 'project_image', type_='foreignkey')
    op.drop_column('project_image', 'project_id')
    # ### end Alembic commands ###
