"""auto

Revision ID: 935f35b1107e
Revises: 0645a13bbab5
Create Date: 2024-04-03 14:42:46.979455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935f35b1107e'
down_revision: Union[str, None] = '0645a13bbab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_details',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tge_date', sa.DateTime(), nullable=False),
    sa.Column('tge_percent', sa.Integer(), nullable=False),
    sa.Column('cliff', sa.Integer(), nullable=False),
    sa.Column('vesting', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('token_description', sa.String(), nullable=False),
    sa.Column('total_supply', sa.Integer(), nullable=False),
    sa.Column('initial_supply', sa.String(), nullable=False),
    sa.Column('market_cap', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['launchpad_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_details')
    # ### end Alembic commands ###
