"""Add supported tokens

Revision ID: 36f1648d786c
Revises: 69e3f91412f8
Create Date: 2024-05-17 18:53:46.494479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f1648d786c'
down_revision: Union[str, None] = '931b35d41813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supported_tokens',
    sa.Column('id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('chain_id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_address', 'chain_id', name='uc_token_address_chain_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_token_address_chain_id', 'supported_tokens')
    op.drop_table('supported_tokens')
    # ### end Alembic commands ###
