"""add token_address for project

Revision ID: f4391989d839
Revises: e7fcc5dc2c16
Create Date: 2024-04-22 13:08:07.596334

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4391989d839"
down_revision: Union[str, None] = "e7fcc5dc2c16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("launchpad_project", sa.Column("token_address", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("launchpad_project", "token_address")
    # ### end Alembic commands ###
