"""decimal points

Revision ID: b71fb4f1c1cf
Revises: 1a6f76d1a76c
Create Date: 2024-06-21 11:11:11.312756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b71fb4f1c1cf'
down_revision: Union[str, None] = '1a6f76d1a76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extra_points', 'points',
               existing_type=sa.BIGINT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('(0)::bigint'))
    op.alter_column('points_history', 'points_before',
               existing_type=sa.BIGINT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('(0)::bigint'))
    op.alter_column('points_history', 'amount',
               existing_type=sa.BIGINT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('(0)::bigint'))
    op.alter_column('points_history', 'points_after',
               existing_type=sa.BIGINT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('(0)::bigint'))
    op.alter_column('profiles', 'points',
               existing_type=sa.BIGINT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('(0)::bigint'))
    op.alter_column('profiles', 'ref_points',
               existing_type=sa.BIGINT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('(0)::bigint'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'ref_points',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0)::bigint'))
    op.alter_column('profiles', 'points',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0)::bigint'))
    op.alter_column('points_history', 'points_after',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text('(0)::bigint'))
    op.alter_column('points_history', 'amount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text('(0)::bigint'))
    op.alter_column('points_history', 'points_before',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text('(0)::bigint'))
    op.alter_column('extra_points', 'points',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text('(0)::bigint'))
    # ### end Alembic commands ###
