"""Add kyb info

Revision ID: 95aa5d496bd4
Revises: 36f1648d786c
Create Date: 2024-05-22 13:24:30.861441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95aa5d496bd4'
down_revision: Union[str, None] = '36f1648d786c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('launchpad_project', sa.Column('kyb_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('launchpad_project', 'kyb_info')
    # ### end Alembic commands ###
