"""auto

Revision ID: 4d4d74d067de
Revises: 6e968245c0ea
Create Date: 2024-03-27 17:38:09.997200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4d74d067de'
down_revision: Union[str, None] = '6e968245c0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('project_id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['launchpad_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    project_type_enum = sa.Enum('DEFAULT', 'PARTNERSHIP_PRESALE', name='projecttype')
    project_type_enum.create(op.get_bind())
    op.add_column('launchpad_project', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('launchpad_project', sa.Column('token_sale_details', sa.Text(), nullable=True))
    op.add_column('launchpad_project', sa.Column('project_type', sa.Enum('DEFAULT', 'PARTNERSHIP_PRESALE', name='projecttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('launchpad_project', 'project_type')
    op.drop_column('launchpad_project', 'token_sale_details')
    op.drop_column('launchpad_project', 'description')
    op.drop_table('link')
    # ### end Alembic commands ###
