"""tmp extra points

Revision ID: 1fa85876a639
Revises: 0dec9901fae0
Create Date: 2024-05-31 17:48:30.822639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa85876a639'
down_revision: Union[str, None] = 'b7dda864b901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE operationreason AS ENUM ('ERR_COMPENSATION', 'BLASTBOX', 'OTHER_GIVEAWAY')")
    op.create_table('extra_points',
    sa.Column('id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('profile_id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('points', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), server_default=sa.text('0::bigint'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['tmp_profiles.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['launchpad_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_extra_points_profile_id_project_id', 'extra_points', ['profile_id', 'project_id'], unique=True)
    op.add_column('tmp_points_history', sa.Column('operation_reason', sa.Enum('ERR_COMPENSATION', 'BLASTBOX', 'OTHER_GIVEAWAY', name='operationreason'), nullable=True))
    op.add_column('tmp_points_history', sa.Column('project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tmp_points_history', 'launchpad_project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tmp_points_history', type_='foreignkey')
    op.drop_column('tmp_points_history', 'project_id')
    op.drop_column('tmp_points_history', 'operation_reason')
    op.drop_index('idx_extra_points_profile_id_project_id', table_name='extra_points')
    op.drop_table('extra_points')
    op.execute("DROP TYPE IF EXISTS operationreason")
    # ### end Alembic commands ###
