"""history stake

Revision ID: fc9df0701eb9
Revises: f4391989d839
Create Date: 2024-04-30 10:51:57.218857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9df0701eb9'
down_revision: Union[str, None] = 'f4391989d839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stake_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('type', sa.Enum('UNSTAKE', 'STAKE', 'CLAIM_REWARDS', name='historystaketype'), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('chain_id', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), server_default=sa.text('0::bigint'), nullable=False),
    sa.Column('user_address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='check_positive_amount'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stake_history_user_address'), 'stake_history', ['user_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stake_history_user_address'), table_name='stake_history')
    op.drop_table('stake_history')
    op.execute("DROP TYPE historystaketype")
    # ### end Alembic commands ###
