"""claim date

Revision ID: 257075b44257
Revises: a1ac9d016154
Create Date: 2024-05-24 11:44:06.830219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257075b44257'
down_revision: Union[str, None] = 'a1ac9d016154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('launchpad_project', sa.Column('claim_start_at', sa.DateTime(), nullable=True))
    op.add_column('launchpad_project', sa.Column('claim_end_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('launchpad_project', 'claim_end_at')
    op.drop_column('launchpad_project', 'claim_start_at')
    # ### end Alembic commands ###
