"""enhance launchpad events

Revision ID: cbdd322cda26
Revises: 3253ef8aa930
Create Date: 2024-07-02 02:06:05.049313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cbdd322cda26'
down_revision: Union[str, None] = '3253ef8aa930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('launchpad_contract_events', sa.Column('project_id', sa.String(), nullable=True))
    op.execute("CREATE TYPE launchpadeventprojecttype AS ENUM ('DEFAULT', 'MULTICHAIN');")
    op.add_column('launchpad_contract_events', sa.Column('project_type', sa.Enum('DEFAULT', 'MULTICHAIN', name='launchpadeventprojecttype'), server_default="DEFAULT", nullable=False))
    op.add_column('launchpad_contract_events', sa.Column('chain_id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=True))
    op.alter_column('launchpad_contract_events', 'token_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key('launchpad_contract_events_project_id_fkey', 'launchpad_contract_events', 'launchpad_project', ['project_id'], ['id'])
    op.add_column('launchpad_project', sa.Column('bonus_for_ido_purchase', sa.Float(), server_default='2.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('launchpad_contract_events_project_id_fkey', 'launchpad_contract_events', type_='foreignkey')
    op.execute("DELETE FROM launchpad_contract_events WHERE token_address IS NULL;")
    op.alter_column('launchpad_contract_events', 'token_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('launchpad_contract_events', 'project_type')
    op.drop_column('launchpad_contract_events', 'project_id')
    op.drop_column('launchpad_contract_events', 'chain_id')
    op.drop_column('launchpad_project', 'bonus_for_ido_purchase')
    op.execute("DROP TYPE launchpadeventprojecttype")
    # ### end Alembic commands ###
