"""vesting dates

Revision ID: 0822cc2cd3fc
Revises: 62574cdc4f2a
Create Date: 2024-06-04 22:49:10.903414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0822cc2cd3fc'
down_revision: Union[str, None] = '62574cdc4f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_details', sa.Column('vesting_start', sa.DateTime(), nullable=True))
    op.add_column('token_details', sa.Column('vesting_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_details', 'vesting_end')
    op.drop_column('token_details', 'vesting_start')
    # ### end Alembic commands ###
