"""empty message

Revision ID: f68f01901268
Revises: e7fcc5dc2c16
Create Date: 2024-04-15 14:52:24.056976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68f01901268'
down_revision: Union[str, None] = 'e7fcc5dc2c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('launchpad_project', 'total_raise', new_column_name='raise_goal')
    op.add_column('launchpad_project', sa.Column('raise_goal_on_launchpad', sa.DECIMAL(), nullable=True))
    op.add_column('launchpad_project', sa.Column('total_raised', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('launchpad_project', 'raise_goal', new_column_name='total_raise')
    op.drop_column('launchpad_project', 'total_raised')
    op.drop_column('launchpad_project', 'raise_goal_on_launchpad')
    # ### end Alembic commands ###
