"""create balances_sync table

Revision ID: aeb989133559
Revises: 49707fe8417d
Create Date: 2024-06-30 15:55:41.533289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb989133559'
down_revision: Union[str, None] = '49707fe8417d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances_sync',
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('locked_balance', sa.Text(), nullable=True),
    sa.Column('staking_balance', sa.Text(), nullable=True),
    sa.Column('staking_percent', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime()),
    sa.Column('should_be_synced', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_index(op.f('ix_balances_sync_should_be_synced'), 'balances_sync', ['should_be_synced'], unique=False)
    op.create_index(op.f('ix_balances_sync_staking_percent'), 'balances_sync', ['staking_percent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balances_sync_staking_percent'), table_name='balances_sync')
    op.drop_index(op.f('ix_balances_sync_should_be_synced'), table_name='balances_sync')
    op.drop_table('balances_sync')
    # ### end Alembic commands ###
