"""auto

Revision ID: a45d979f71d7
Revises: ba560db8cb95
Create Date: 2024-04-04 17:40:06.274701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.models import FileType


# revision identifiers, used by Alembic.
revision: str = 'a45d979f71d7'
down_revision: Union[str, None] = 'ba560db8cb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('launchpad_project', 'logo_url',
               existing_type=sa.TEXT(),
               type_=FileType(),
               existing_nullable=True)
    op.alter_column('project_image', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_image', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('launchpad_project', 'logo_url',
               existing_type=FileType(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
