"""adds is_visible flag to projects

Revision ID: 1753b23ed0cd
Revises: e1c9edea5a23
Create Date: 2024-06-06 13:10:37.822755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1753b23ed0cd'
down_revision: Union[str, None] = 'e1c9edea5a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('launchpad_project', sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_launchpad_project_is_visible'), 'launchpad_project', ['is_visible'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_launchpad_project_is_visible'), table_name='launchpad_project')
    op.drop_column('launchpad_project', 'is_visible')
    # ### end Alembic commands ###
