"""auto

Revision ID: 0645a13bbab5
Revises: 08723b294879
Create Date: 2024-04-02 16:48:54.554699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0645a13bbab5'
down_revision: Union[str, None] = '08723b294879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('launchpad_project', sa.Column('ticker', sa.String(), nullable=True))
    op.add_column('launchpad_project', sa.Column('points_reward_start_at', sa.DateTime(), nullable=True))
    op.add_column('launchpad_project', sa.Column('points_reward_end_at', sa.DateTime(), nullable=True))
    op.alter_column('launchpad_project', 'token_price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('launchpad_project', 'token_price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.drop_column('launchpad_project', 'points_reward_end_at')
    op.drop_column('launchpad_project', 'points_reward_start_at')
    op.drop_column('launchpad_project', 'ticker')
    # ### end Alembic commands ###
