"""empty message

Revision ID: 210fb733bd2f
Revises: c4318467f675
Create Date: 2024-03-30 15:17:08.336383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '210fb733bd2f'
down_revision: Union[str, None] = 'c4318467f675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = inspect(bind)
    columns = insp.get_columns(table_name)
    return any(c["name"] == column_name for c in columns)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('onramp_orders', 'received_amount'):
        op.add_column('onramp_orders', sa.Column('received_amount', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onramp_orders', 'received_amount')
    # ### end Alembic commands ###
