"""add transactions

Revision ID: 3253ef8aa930
Revises: e522a9d71eb9
Create Date: 2024-06-28 02:21:36.109328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3253ef8aa930'
down_revision: Union[str, None] = 'aeb989133559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('user_address', sa.Text(), nullable=False),
    sa.Column('chain_id', sa.BigInteger().with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('hash', sa.Text(), nullable=True),
    sa.Column('payment_token_address', sa.String(), nullable=True),
    sa.Column('payment_amount', sa.Text(), nullable=False),
    sa.Column('payment_amount_usd', sa.Text(), nullable=True),
    sa.Column('amount_project_token', sa.Text(), nullable=True),
    sa.Column('token2usd_rate', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('payment_currency', sa.Text(), nullable=True),
    sa.Column('currency2usd_rate', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), server_default='crypto', nullable=True),
    sa.Column('points_paid_at', sa.DateTime(), nullable=True),
    sa.Column('points_amount', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0::decimal'), nullable=False),
    sa.Column('ref_points_amount', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0::decimal'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('invalid_reason', sa.Enum('TXN_FAILED', 'BAD_TX_RECIPIENT', name='transactioninvalidreason'), nullable=True),
    sa.Column('onramp_order_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['launchpad_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash', name='ux_transactions_txn_hash')
    )
    op.create_index(op.f('ix_transactions_user_address'), 'transactions', ['user_address'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_address'), table_name='transactions')
    op.drop_constraint("ux_transactions_txn_hash", table_name='transactions')
    op.drop_table('transactions')
    op.execute("DROP TYPE transactioninvalidreason")
    # ### end Alembic commands ###
