"""auto

Revision ID: 1d0fe7ddf14b
Revises: 210fb733bd2f
Create Date: 2024-04-01 16:28:17.550598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d0fe7ddf14b'
down_revision: Union[str, None] = '210fb733bd2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('onramp_orders', 'onramp_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('onramp_order', 'onramp_orders')
    # ### end Alembic commands ###
