"""empty message

Revision ID: 1389be6865b3
Revises: 14867a15741b
Create Date: 2024-04-11 19:43:39.819705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1389be6865b3'
down_revision: Union[str, None] = '14867a15741b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute(sa.text("ALTER TABLE launchpad_project ALTER COLUMN project_type TYPE projecttype USING project_type::projecttype;"))
    connection.execute(sa.text("DROP TYPE projecttype_old;"))
# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute(sa.text("ALTER TABLE launchpad_project ALTER COLUMN project_type TYPE text USING project_type::text;"))
    connection.execute(sa.text("CREATE TYPE projecttype AS ENUM ('DEFAULT', 'PARTNERSHIP_PRESALE');"))
    # ### end Alembic commands ###
