"""removes some fields to profile

Revision ID: e1c9edea5a23
Revises: 7f9330cf25b5
Create Date: 2024-06-05 11:19:10.330952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1c9edea5a23'
down_revision: Union[str, None] = '7f9330cf25b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'device_resolution')
    op.drop_column('profiles', 'device_type')
    op.drop_column('profiles', 'browser_referrer')
    op.drop_column('profiles', 'ip')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('ip', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('browser_referrer', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('device_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('device_resolution', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
