name: Pre-commit checks

on: push
#  pull_request_target:
#    types: [opened, synchronize]

jobs:
  pre-commit:
    name: Pre-commit hook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install dev dependencies
        run: |
          $HOME/.poetry/bin/poetry install --no-root --only dev
          $HOME/.poetry/bin/poetry run 'pre-commit install'
          $HOME/.poetry/bin/poetry run 'pre-commit run --all'

      - name: Run pre-commit hook
        run: pre-commit run -a

      - name: Check for pre-commit errors
        run: echo "Pre-commit checks passed"
